### ISSUE TITLE
Index/Site navigation in top right corner doesn't work. 

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#10]
Clicked it, nothin' happened

**Comment by easherma** [comment]
@pkrawc this appears to be a placeholder for the menu that doesn't appear to have been translated from designs yet?

**Comment by pkrawc** [comment]
@easherma I'm taking care about this when I get home tonight unless you want to tackle it at Hack night

**Comment by easherma** [comment]
All yours!
