### ISSUE TITLE
Create preview metadata for links to articles, videos

### ISSUE THREAD

**Issue by easherma** [state-matters/state-matters-website#102]
@KacieSmi mentioned a high priority item that I'd say is a medium lift

Social media previews for article and video links just show the preview for the main site. The URL link itself works just fine. 

I belive these are controlled through meta properties that we'd just have to dynamically generate for each article? I'm thinking article title, maybe author, feature image from the article or video?

**Comment by pkrawc** [comment]
@easherma Yep and I believe we already use `react-helmet` to set the title tag of the page dynamically so you should be able to use that pretty easily.

**Comment by grace000** [comment]
@pkrawc @easherma Kacie said that just the title and image is fine, but  I wanted to make sure that this looks okay before I change anything with the videos.

**Comment by easherma** [comment]
@grace000 That should be fine for videos as well, I believe the videos have a preview thumbnail. More relevant detail here: 
https://developers.facebook.com/docs/sharing/webmasters/
