### ISSUE TITLE
Footer Issues - non working links/typos

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#12]
None of the links in black box on the left exist/work "About Submit Careers Blog" -- I'd suggest just not including those in the first roll out if possible. 

Donate button in footer goes to "Page not found"

Newsletter button in footer goes to "Page not found" and there's atypo "new letter"

**Comment by pkrawc** [comment]
@easherma This can be closed right?

**Comment by easherma** [comment]
yep, the only thing left to resolve is the weird donate layout, but it works
