### ISSUE TITLE
Missing the banner Launch Party announcement 

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#14]

**Comment by pkrawc** [comment]
@KacieSmi We're happy if this is just hard coded for now correct?

**Comment by KacieSmi** [comment]
Sure. Sounds good! :)

**Comment by pkrawc** [comment]
@grace000 Wanna tackle this one?

**Comment by pkrawc** [comment]
Also, do you have access to the invision prototype?

**Comment by KacieSmi** [comment]
I added her!   Also the link for tickets: https://sleeping-village.com/calendar/state-matters-launch-party/

**Comment by grace000** [comment]
@pkrawc Do you have a mock up of this or have you already selected banner colors?

**Comment by KacieSmi** [comment]
@grace000  https://projects.invisionapp.com/d/main#/console/13466013/299492223/preview

**Comment by pkrawc** [comment]
@grace000 Yea, there's a mockup in a tool called invision, which is a prototyping tool used for design handoff. @KacieSmi should have added you to the project.

**Comment by pkrawc** [comment]
Ha, she got there just before me.

**Comment by grace000** [comment]
Thanks!

**Comment by grace000** [comment]
@pkrawc my main concerns are the banner position and responsiveness. Any recommendations for placing the banner between two components? I see that the circle on the right has been transformed from the hero.js section, but when I added content to the hero section, it interfered with the main header.

**Comment by pkrawc** [comment]
@grace000 This is like 99.9995% of the way there. You have a `margin-top: 2rem;` on the `LaunchBanner` component. All you have to do is set a negative margin-top. When I put a -10rem on the margin-top it looks pretty choice.

**Comment by grace000** [comment]
@pkrawc  around a page width of 675px, the banner starts to cut off the main header up top. I'm going to add media queries to reduce the negative margin. Overall, it looks like the first section of the home page should be longer and the font should be smaller in order to match the mock-up.
