### ISSUE TITLE
Get rid of featured video / have educational videos at the top?  

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#15]

**Comment by pkrawc** [comment]
@KacieSmi Is this what we're wanting still? It's true there are no/one bill videos currently. It'll be a pretty easy change to rearrange the BillList with the LessonList

@easherma What do you think about this?

**Comment by KacieSmi** [comment]
Yes! Educational videos at the top!

**Comment by pkrawc** [comment]
This was fixed by @easherma. I'm closing this now.
