### ISSUE TITLE
Handle image captions/subtitles

### ISSUE THREAD

**Issue by easherma** [state-matters/state-matters-website#17]
It came up during Contentful import that there isn't a standard way to identify image captions in Markdown.

Couple workaround options that I can see:

- Use the insert table feature in Contenful, choose one column, two rows, and put the subtitle in the second row
    - Nice thing about this is it is writer friendly, but kind of annoying? It also still keeps the styling fairly limited without us hacking it. 
- Come up with a standard 'tag' for our writers to use that we can parse:
   - i.e. `Source: [text description of link](website.com)` renders as " Source: [text description of link](website.com) ", but if we wrap it in something like `makecaption[Source: [text description of link](website.com)] ` that renders as makecaption[Source: [text description of link](website.com)] by default but it looks like we could (according to [plugin docs](https://www.npmjs.com/package/markdown-to-jsx#optionsoverrides---override-any-html-tags-representation)) parse that out of the the markdown and override it with a caption component that we make.
   - Actually as I was thinking about it this would be slicker if we just had writers use the quotes feature in Markdown to make a title (mouse over this to see what I mean):
![graph](https://cdn-images-1.medium.com/max/1400/1*0KOCbN8asda_074Wd0fpyw.png "Title on mouseover that we could probably grab out of the rendered html and stick underneath the image")
- Have our writers use figure and [figure caption html5](https://www.w3schools.com/TAgs/tag_figcaption.asp) tags, then style as needed. This is probably the simplest option but it means a little extra work from writers/editors.

**Comment by pkrawc** [comment]
@easherma I propose the title for this I think. It's totally possible to parse the markdown and replace a standard tag with a custom component but I don't know if it's needed for this. We could also honestly just use the alt-text of the image.

As an aside the replacement feature in `markdown-to-jsx` is how I propose to do the glossary feature.

`[alt text for image](https://image-url.jpg "title text")`

Either the title or the alt can be pulled out.
