### ISSUE TITLE
About Page formatting is off/bizarre. Add contact form? 

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#24]
Some missing information and wonky formatting on the About Page. Sections are too close together and the indentation is off. 

_________________________

Who is State Matters?
We are an eclectic group of artists, designers, developers, policy wonks, and writers. **Meet our team.** < link to team page??? 

What do we do?
We create high-quality videos that:
Explain the most impactful, state legislation being proposed in Springfield.
Explain the legislative process and how government operates.
Inform constituents how to engage with state legislators. **[CAPITAL I at the beginning!]**

Work with us
Our team is up for a challenge and we’re always adding new voices and perspectives to our team.
Are you an artist who wants to make a difference? We are too! Let’s join forces.

**Contact us: 
CONTACT FORM? that goes to info@statematters.org**

**Comment by pkrawc** [comment]
@KacieSmi @easherma I'm taking this issue now. 🌮
