### ISSUE TITLE
Copy fixes for the home page 

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#27]
OH MY GOD I HATE THAT I CAN'T COPY TEXT IN WHY IS THIS THE WORST THING THAT EVER WAS. 
[Website copy changes.docx](https://github.com/state-matters/state-matters-website/files/2086377/Website.copy.changes.docx)

**Comment by KacieSmi** [comment]
Also in the footer "statematter.org" should be "statematters.org"  🥇

**Comment by easherma** [comment]
HOME PAGE

We create video content and briefs on the most pressing political issues & laws that affect you.
>>We clarify Illinois government with short videos & helpful summaries on the issues that matter to you! 

Educational Videos >> Illinois Government 101
