### ISSUE TITLE
Add social media icons! 

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#28]
Need to add links to our twitter, instagram, and facebook!

**Comment by pkrawc** [comment]
@KacieSmi Can we post the urls to those things here? @easherma we're using `react-feather` for icons in the app so far.

**Comment by KacieSmi** [comment]
Facebook:   https://www.facebook.com/statematters/
Twitter: https://twitter.com/state_matters
Instagram: https://www.instagram.com/statematters/
Youtube.... I dunno how to get the channel url @pkrawc
