### ISSUE TITLE
Logo should be white and turn black on scroll

### ISSUE THREAD

**Issue by crodrgz** [state-matters/state-matters-website#29]
![image](https://user-images.githubusercontent.com/40127298/41195721-a97c2a98-6bf8-11e8-9da1-906030cba48b.png)

I'm sure you're getting to it but on scroll header should be fixed, see invision: https://invis.io/Q8G09OABSN5#/299490277_Hover_Interactions

**Comment by pkrawc** [comment]
Fixed with #42
