### ISSUE TITLE
text styling - change to Poppins regular @ 32 pt

### ISSUE THREAD

**Issue by crodrgz** [state-matters/state-matters-website#30]
![image](https://user-images.githubusercontent.com/40127298/41195822-46251fa2-6bfa-11e8-8449-2e34073355f3.png)

**should be poppins regular 32**

**Comment by pkrawc** [comment]
I'll change this. I believe this was because if it's Poppins it would be the only headline that is Poppins @crodrgz.

_also, welcome to Github!_
