### ISSUE TITLE
Style CTAs and simplify interaction

### ISSUE THREAD

**Issue by crodrgz** [state-matters/state-matters-website#31]
This should be 14 pt, Poppins Bold.

Also we should simplify the interaction. Seeing it everywhere is a little crazy. Can we make it so it just moves to the right away from the text like 4 pixels with an ease on hover?

![image](https://user-images.githubusercontent.com/40127298/41195832-786df9a2-6bfa-11e8-82a4-5cc4cbb7bb69.png)

**Comment by easherma** [comment]
I would suggest we wait until after launch for this, we already spent time implementing the current behavior and have plenty else to tackle in a limited timeframe

**Comment by crodrgz** [comment]
Sure. Could you make the buttons text-size: 14, Poppins bold please! @easherma @pkrawc

**Comment by pkrawc** [comment]
I've updated this + updated the interaction
