### ISSUE TITLE
Article Page: Style text

### ISSUE THREAD

**Issue by crodrgz** [state-matters/state-matters-website#34]
Make the max width for text 640px wide and in the center of the page
Image max width should be ~840px wide

Section titles should be **font-size: 22px, Poppins Medium**

**Body Copy** should be **font-size 16px, Poppins Light**

spacing between sections
![image](https://user-images.githubusercontent.com/40127298/41196197-8d27fa9a-6c00-11e8-8532-c1e8f5bcdcf4.png)

**Comment by pkrawc** [comment]
@easherma @crodrgz It's great that these rules are becoming more defined. I suggest we create a wiki / make sure we put these max-widths and sizings in the `theme.js` file so they can be easily consumed through the whole app.

**Comment by pkrawc** [comment]
@crodrgz 22 / 16 font size is pretty small. Currently body is 18px (1.5rem) and the smallest headline is 24px (2rem). Is this sufficient? If you look at Medium or pretty much any other text heavy site they're all carrying body copy 18px or above (I believe Medium is 24px).

**Comment by crodrgz** [comment]
Yo! 16 is pretty standard. I’m working on the global website for McDonald’s
and 16 is the body copy, and actually quite large for accessibility
purposes. I designed with accessibility in mind. 👀 that should all be
fine.

Also please look close at spacing on invision for that middle section.

Thanks for working on it so hard man, I really appreciate it/you.

**Comment by pkrawc** [comment]
![image](https://user-images.githubusercontent.com/7158581/41325358-693b70e0-6e7f-11e8-9ea7-e8e59e6a8ba9.png)

@easherma @jonrogoff and @grace000 who wants to tackle getting the base styles of the site in `baseStyles.js` (weird that styling is in a js file I know) to look like @crodrgz's image above?

**Comment by pkrawc** [comment]
Button's aren't in the scope of this. Just h1 - h5,  p, and p.medium tags

**Comment by pkrawc** [comment]
Whoops, did not mean to close this.

**Comment by easherma** [comment]
I might advocate for article pages/body text in articles to have a different layout than the rest of the site for readability

**Comment by crodrgz** [comment]
See my comment on articles @eric Sherman. I think I proposed specific
guidelines around that
