### ISSUE TITLE
Menu should close/hide once it navigates to new page

### ISSUE THREAD

**Issue by easherma** [state-matters/state-matters-website#44]

**Comment by easherma** [comment]
@pkrawc I can probably implement this if you point me to where ( something in CSSTransitions? or do I need to write a closing style/function)

**Comment by pkrawc** [comment]
@easherma I took care about it. The transition will happen regardless of what closes the header.

You can see I've hooked into the `componentDidUpdate` method and am checking to see if the browser location has changed, if so, close the header by changing state.
