### ISSUE TITLE
Bulletpoints in articles/lessons/body text

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#68]
bulletpoints are manifesting strangely. 
<img width="946" alt="screen shot 2018-06-24 at 6 08 22 pm" src="https://user-images.githubusercontent.com/36746528/41824656-b79f2368-77d9-11e8-8f4f-d96df6db7031.png">

**Comment by pkrawc** [comment]
@KacieSmi What lesson or article is this in?

**Comment by easherma** [comment]
Resolved via discussion
