### ISSUE TITLE
Subscription button remains at "Thank you" instead of resetting

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#69]
I used the Sign up for newsletter button two days ago. But when I clicked on it today - it still came up with a thank you for subscribing message! 
<img width="822" alt="screen shot 2018-06-24 at 6 27 20 pm" src="https://user-images.githubusercontent.com/36746528/41824806-65996ddc-77dc-11e8-9e46-891dd9d1acec.png">

**Comment by pkrawc** [comment]
@KacieSmi Would you like for it to let you subscribe again?

This was on purpose to keep people from trying to subscribe a bunch of times.

**Comment by KacieSmi** [comment]
Gotcha. Well it makes it so we can't set up a laptop and have folks subscribe at events on the same laptop/ipad. I noticed today because one of Cliff's friends came over and wasn't on the newsletter and I said "I can fix that right now! Ooop nevermind I can't".

**Comment by KacieSmi** [comment]
Is spam signup a common issue? Also I think Mailchimp filters out duplicates.

**Comment by pkrawc** [comment]
Okay, so barring other thoughts I'm going to implement like this.
```
subscribe => alreadySubscribed ? "please subscribe with a different email, that one is already on our list!" : successfulSubscribe => "Thanks for subscribing {email}! Click here to register another email."
```
