### ISSUE TITLE
Build ArticleList for Homepage

### ISSUE THREAD

**Issue by pkrawc** [state-matters/state-matters-website#7]

**Comment by pkrawc** [comment]
Is there any progress on this farther than what is on `develop`?

**Comment by easherma** [comment]
@pkrawc no, I have been otherwise engaged and was under the impression that you had overtaken me on that feature? I could jump back in if needed.

**Comment by pkrawc** [comment]
@easherma No It's done on my end. I just kept it open to make sure that I wasn't overriding work done I was out of the loop for. I'll close this in a bit.

**Comment by pkrawc** [comment]
Yep. This is done. Will probably need cleanup in the near future but it's functional now.
