### ISSUE TITLE
Remove download option from videos 

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#74]
Currently there's an option to direct download the videos. No please! :)

**Comment by pkrawc** [comment]
@KacieSmi We'll never be able to prevent downloads on videos truly. A good step at preventing the layman from doing it would be to use YouTube. But even then there are easily gotten tools that will help you download a video.

**Comment by KacieSmi** [comment]
Gotcha! But we don't need to make it easy by having it as an option?

**Comment by easherma** [comment]
the option exists by default in chrome as a button, doesn't show up in other browsers. we can probably hide it as a bit of a patch
