### ISSUE TITLE
Videos aren't all reachable on home page unless you zoom out. 

### ISSUE THREAD

**Issue by KacieSmi** [state-matters/state-matters-website#82]

**Comment by pkrawc** [comment]
Zoom out? That shouldn't be possible.

**Comment by KacieSmi** [comment]
It's an issue of there not being clear navigation symbols that you can drag/navigate to the side. I've had 3 different millennials tell me this is an issue. So... we just need to make it clear.

**Comment by pkrawc** [comment]
Yep. That's totally valid. Still concerned if you can zoom out of the page. Is this on mobile?
